
services:
  # FOR LOCAL DEVELOPMENT ENV FOR VSCODE CONTAINERIZATION
  frontend-local:
    build:
      context: .  # Path to Dockerfile.local
      dockerfile: .devcontainer/Dockerfile.local
    ports:
      - "5173:5173"  # Map Vite dev server port
    volumes:
      - ./:/app       # Mount local directory for live reloading
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env.local
  # FOR DEVELOPMENT SITE OF FRONTEND
  frontend-dev:
    build:
      context: .  # Path to Dockerfile.dev
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"  # Map Vite dev server port
    volumes:
      - ./dist:/app/dist # Mounts the local dist directory to the container
    environment:
      NODE_ENV: development
    env_file:
      - .env.dev
  # FOR PROD FRONTEND PROD SETUP
  frontend-prod:
     # Service for building the React app (production build)
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile for the production build
    volumes:
      - ./dist:/app/dist # Mounts the local dist directory to the container
    environment:
      NODE_ENV: production